/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.usuarios;
import dao.usuariosdao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Debora
 */
public class TelaCadUsuario extends javax.swing.JInternalFrame {

    
private  class jTable1 {

        public jTable1() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));
        usuariosdao a = new usuariosdao();
     
        modelo.setNumRows(0);
    
     for (usuarios x : a.read()) {
     modelo.addRow(new Object[]{
        
       x.getUsu_id(),
       x.getUsu_nome(),
       x.getUsu_sobrenome(),
       x.getUsu_morada(),
       x.getUsu_fone(),
       x.getUsu_email(),
       x.getUsu_profissao(),
        });           
        }
        }
    }
    /**
     * Creates new form TelaCadUsuario
     */
    public TelaCadUsuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        tfsobrenome = new javax.swing.JTextField();
        tffone = new javax.swing.JTextField();
        tfprofissao = new javax.swing.JTextField();
        tfmorada = new javax.swing.JTextField();
        btinserir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        btalterar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btconsulta = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inclusão de Usuário");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel2.setText("Morada");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel5.setText("Profissao");

        btinserir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btinserir.setText("Inserir Dados");
        btinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinserirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel7.setText("Sobrenome:");

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("                                                                                                           Dados Pessoais");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel9.setText("                                                                                                                Contato");
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel10.setText("Email:");

        btalterar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btexcluir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_Usu", "Nome", "Sobrenome", "Telefone", "Email", "Morada", "Profissão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btconsulta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btconsulta.setText("Consultar");
        btconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfprofissao, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tffone, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(294, 294, 294))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btinserir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btalterar)
                .addGap(85, 85, 85)
                .addComponent(btexcluir)
                .addGap(85, 85, 85)
                .addComponent(btconsulta)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tfmorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tffone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfprofissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btinserir)
                    .addComponent(btalterar)
                    .addComponent(btexcluir)
                    .addComponent(btconsulta))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinserirActionPerformed
//botao inserir - ok
     usuarios u = new usuarios();
     usuariosdao dao = new usuariosdao();
     u.setUsu_nome(tfnome.getText());
     u.setUsu_sobrenome(tfsobrenome.getText());
     u.setUsu_morada(tfmorada.getText());
     u.setUsu_fone(tffone.getText());
     u.setUsu_email(tfemail.getText());
     u.setUsu_profissao(tfprofissao.getText());
     dao.create(u);

     jTable1.setValueAt(tfnome.getText(),jTable1.getSelectedRow(),1);
     jTable1.setValueAt(tfsobrenome.getText(),jTable1.getSelectedRow(),2);
     jTable1.setValueAt(tfmorada.getText(),jTable1.getSelectedRow(),3);
     jTable1.setValueAt(tffone.getText(),jTable1.getSelectedRow(),4);
     jTable1.setValueAt(tfemail.getText(),jTable1.getSelectedRow(),5);
     jTable1.setValueAt(tfprofissao.getText(),jTable1.getSelectedRow(),6);
     
      tfnome.setText("");
      tfsobrenome.setText("");
      tfmorada.setText("");
      tffone.setText("");
      tfemail.setText("");
      tfprofissao.setText("");
    }//GEN-LAST:event_btinserirActionPerformed

    private void btconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconsultaActionPerformed
        // TODO add your handling code here: botao consultar ok
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    usuariosdao a = new usuariosdao();
    modelo.setNumRows(0);
    
     for (usuarios x : a.read()) {
     modelo.addRow(new Object[]{
        
       x.getUsu_id(),
       x.getUsu_nome(),
       x.getUsu_sobrenome(),
       x.getUsu_morada(),
       x.getUsu_fone(),
       x.getUsu_email(),
       x.getUsu_profissao(),
        });           
        }
    }//GEN-LAST:event_btconsultaActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here: botao alterar ok
        
     if(jTable1.getSelectedRow() != -1){
     usuarios u = new usuarios();
     usuariosdao dao = new usuariosdao(); 
   
     u.setUsu_nome(tfnome.getText());
     u.setUsu_sobrenome(tfsobrenome.getText());
     u.setUsu_morada(tfmorada.getText());
     u.setUsu_fone(tffone.getText());
     u.setUsu_email(tfemail.getText());
     u.setUsu_profissao(tfprofissao.getText());
     u.setUsu_id((int)jTable1.getValueAt(jTable1.getSelectedRow(),0));
     dao.update(u); 
    }else{
       JOptionPane.showMessageDialog(null, "Escolha um usuário para alterar os dados");    
       
     }   
     jTable1.setValueAt(tfnome.getText(),jTable1.getSelectedRow(),1);
     jTable1.setValueAt(tfsobrenome.getText(),jTable1.getSelectedRow(),2);
     jTable1.setValueAt(tfmorada.getText(),jTable1.getSelectedRow(),3);
     jTable1.setValueAt(tffone.getText(),jTable1.getSelectedRow(),4);
     jTable1.setValueAt(tfemail.getText(),jTable1.getSelectedRow(),5);
     jTable1.setValueAt(tfprofissao.getText(),jTable1.getSelectedRow(),6);
     
      tfnome.setText("");
      tfsobrenome.setText("");
      tfmorada.setText("");
      tffone.setText("");
      tfemail.setText("");
      tfprofissao.setText(""); 
     
    }//GEN-LAST:event_btalterarActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        // TODO add your handling code here: ok, funciona bem
       
     if(jTable1.getSelectedRow() != -1){
         
     usuarios u = new usuarios();
     usuariosdao dao = new usuariosdao();
     u.setUsu_id((int) jTable1.getValueAt(jTable1.getSelectedRow(),0));
     dao.delete(u);   
         
      tfnome.setText("");
      tfsobrenome.setText("");
      tfmorada.setText("");
      tffone.setText("");
      tfemail.setText("");
      tfprofissao.setText("");
            
     }else{
         JOptionPane.showMessageDialog(null, "Selecione um usuário para excluir");
     }   
    }//GEN-LAST:event_btexcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here: evento do mouse
     if(jTable1.getSelectedRow() != -1){ 
         
      tfnome.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(),1)));
      tfsobrenome.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
      tfmorada.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
      tffone.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
      tfemail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
      tfprofissao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString()); 
     }   
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here: evento do teclado
      if(jTable1.getSelectedRow() != -1){ 
         
      tfnome.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(),1)));
      tfsobrenome.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
      tfmorada.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
      tffone.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
      tfemail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
      tfprofissao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString()); 
     }       
    }//GEN-LAST:event_jTable1KeyPressed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btconsulta;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btinserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tffone;
    private javax.swing.JTextField tfmorada;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tfprofissao;
    private javax.swing.JTextField tfsobrenome;
    // End of variables declaration//GEN-END:variables
}
