/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.modalidades;
import dao.modalidadesdao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Debora
 */
public class TelaModalidades extends javax.swing.JInternalFrame {
    /**
     * Creates new form TelaCadUsuario
     */
    public TelaModalidades() {
        initComponents();
        DefaultTableModel mode = (DefaultTableModel)table_modali.getModel();
        table_modali.setRowSorter(new TableRowSorter(mode));
        modalidadesdao dao = new modalidadesdao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfnomeM = new javax.swing.JTextField();
        tfinstrutor = new javax.swing.JTextField();
        tfvalor = new javax.swing.JTextField();
        btinserir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btalterar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_modali = new javax.swing.JTable();
        btconsulta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfdata = new javax.swing.JTextField();

        setBackground(new java.awt.Color(180, 141, 175));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tabela de Modalidades");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/musculacao-renato.jpg"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(939, 696));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setText("Nome da Modalidade:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel2.setText("Valor/Hora:");

        btinserir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btinserir.setText("Inserir Dados");
        btinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinserirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel7.setText("Nome do Instrutor:");

        jLabel8.setBackground(new java.awt.Color(234, 195, 239));
        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("                                                                                             Tabela de Modalidades da Academia");
        jLabel8.setOpaque(true);

        btalterar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btexcluir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        table_modali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Modalidade", "Modalidade", "Instrutor", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_modali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_modaliMouseClicked(evt);
            }
        });
        table_modali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_modaliKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_modali);

        btconsulta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btconsulta.setText("Consultar");
        btconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconsultaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel4.setText("Data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btinserir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btalterar)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfvalor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfnomeM, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdata, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfinstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btexcluir)
                                .addGap(75, 75, 75)
                                .addComponent(btconsulta)))
                        .addGap(14, 14, 14))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnomeM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfinstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)))
                    .addComponent(tfdata, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btalterar)
                        .addComponent(btexcluir)
                        .addComponent(btconsulta)
                        .addComponent(btinserir)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinserirActionPerformed
     modalidades m = new modalidades();//ok
     modalidadesdao dao = new modalidadesdao();
     
     m.setMod_descricao(tfnomeM.getText());
     m.setMod_instrutor(tfinstrutor.getText());
     m.setMod_preco(tfvalor.getText());
     m.setMod_horario(tfdata.getText());
     dao.create(m);

     table_modali.setValueAt(tfnomeM.getText(),table_modali.getSelectedRow(), 1);
     table_modali.setValueAt(tfinstrutor.getText(), table_modali.getSelectedRow(), 2);
     table_modali.setValueAt(tfvalor.getText(), table_modali.getSelectedRow(), 3);
     table_modali.setValueAt(tfdata.getText(),table_modali.getSelectedRow(), 4);

     tfnomeM.setText("");
     tfinstrutor.setText("");
     tfvalor.setText("");
     tfdata.setText("");
    }//GEN-LAST:event_btinserirActionPerformed

    private void btconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconsultaActionPerformed
        // TODO add your handling code here: ok
     DefaultTableModel modelo = (DefaultTableModel) table_modali.getModel();
     modalidadesdao a = new modalidadesdao();
     modelo.setNumRows(0);
     
      for (modalidades x : a.read()) {
      modelo.addRow(new Object[]{
       x.getMod_id(), 
       x.getMod_descricao(),
       x.getMod_instrutor(),
       x.getMod_preco(),
       x.getMod_horario(),
        });    
        }
    }//GEN-LAST:event_btconsultaActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here: 
      if(table_modali.getSelectedRow() != -1){
     modalidades m = new modalidades();
     modalidadesdao dao = new modalidadesdao(); 
   
     m.setMod_descricao(tfnomeM.getText());
     m.setMod_instrutor(tfinstrutor.getText());
     m.setMod_horario(tfdata.getText());
     m.setMod_preco(tfvalor.getText());
     m.setMod_id((int)table_modali.getValueAt(table_modali.getSelectedRow(),0));
     dao.update(m); 
    }else{
       JOptionPane.showMessageDialog(null, "Escolha um campo para alterar: ");    
     }   
     table_modali.setValueAt(tfnomeM.getText(), table_modali.getSelectedRow(),1);
     table_modali.setValueAt(tfinstrutor.getText(), table_modali.getSelectedRow(), 2);
     table_modali.setValueAt(tfdata.getText(), table_modali.getSelectedRow(), 3);
     table_modali.setValueAt(tfvalor.getText(),table_modali.getSelectedRow(), 4);

     tfnomeM.setText("");
     tfinstrutor.setText("");
     tfdata.setText("");
     tfvalor.setText("");
    }//GEN-LAST:event_btalterarActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        // TODO add your handling code here: 
   if(table_modali.getSelectedRow() != -1){
         
     modalidades m = new modalidades();
     modalidadesdao dao = new modalidadesdao();
     m.setMod_id((int) table_modali.getValueAt(table_modali.getSelectedRow(),0));
     dao.delete(m);   
         
     tfnomeM.setText("");
     tfinstrutor.setText("");
     tfdata.setText("");
     tfvalor.setText("");
    }else{
         JOptionPane.showMessageDialog(null, "Selecione uma modalidade para excluir");
     } 
    }//GEN-LAST:event_btexcluirActionPerformed

    private void table_modaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_modaliMouseClicked
        // TODO add your handling code here: evento do mouse
      if(table_modali.getSelectedRow() != -1){ 
         
      tfnomeM.setText(String.valueOf(table_modali.getValueAt(table_modali.getSelectedRow(),1)));
      tfinstrutor.setText(table_modali.getValueAt(table_modali.getSelectedRow(),2).toString());
      tfdata.setText(table_modali.getValueAt(table_modali.getSelectedRow(), 3).toString());
      tfvalor.setText(table_modali.getValueAt(table_modali.getSelectedRow(),4).toString());
      }
    }//GEN-LAST:event_table_modaliMouseClicked

    private void table_modaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_modaliKeyPressed
        // TODO add your handling code here: evento do teclado
      if(table_modali.getSelectedRow() != -1){ 
         
      tfnomeM.setText(String.valueOf(table_modali.getValueAt(table_modali.getSelectedRow(),1)));
      tfinstrutor.setText(table_modali.getValueAt(table_modali.getSelectedRow(),2).toString());
      tfdata.setText(table_modali.getValueAt(table_modali.getSelectedRow(), 3).toString());
      tfvalor.setText(table_modali.getValueAt(table_modali.getSelectedRow(),4).toString());
          }
    }//GEN-LAST:event_table_modaliKeyPressed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btconsulta;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btinserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_modali;
    private javax.swing.JTextField tfdata;
    private javax.swing.JTextField tfinstrutor;
    private javax.swing.JTextField tfnomeM;
    private javax.swing.JTextField tfvalor;
    // End of variables declaration//GEN-END:variables
}
