/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.funcionarios;
import dao.funcionariosdao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Debora
 */
public class TelaCadFuncionario extends javax.swing.JInternalFrame {

    
private  class Table_Func {

        public Table_Func() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Table_Func.getModel();
        Table_Func.setRowSorter(new TableRowSorter(modelo));
        funcionariosdao a = new funcionariosdao();
     
        modelo.setNumRows(0);
    
     for (funcionarios x : a.read()) {
     modelo.addRow(new Object[]{
        
       x.getFunc_id(),
       x.getFunc_nome(),
       x.getFunc_sobrenome(),
       x.getFunc_morada(),
       x.getFunc_fone(),
       x.getFunc_email(),
       });           
        }
        }
    }
    /**
     * Creates new form TelaCadUsuario
     */
    public TelaCadFuncionario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Table_Func.getModel();
        Table_Func.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfnomeF = new javax.swing.JTextField();
        tfsobrenomeF = new javax.swing.JTextField();
        tffoneF = new javax.swing.JTextField();
        tfmoradaF = new javax.swing.JTextField();
        btinserir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfemailF = new javax.swing.JTextField();
        btalterar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Func = new javax.swing.JTable();
        btconsulta = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inclusão de Funcionários");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel2.setText("Morada:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel3.setText("Telefone:");

        btinserir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btinserir.setText("Inserir Dados");
        btinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinserirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel7.setText("Sobrenome:");

        jLabel8.setBackground(new java.awt.Color(153, 153, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("                                                                                                       Dados Pessoais");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(102, 102, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("                                                                                                            Contato");
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel10.setText("Email:");

        btalterar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btexcluir.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Table_Func.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_Usu", "Nome", "Sobrenome", "Telefone", "Email", "Morada", "Modalidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_FuncMouseClicked(evt);
            }
        });
        Table_Func.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Table_FuncKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Func);

        btconsulta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btconsulta.setText("Consultar");
        btconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tffoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tfemailF, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btinserir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btalterar)
                .addGap(85, 85, 85)
                .addComponent(btexcluir)
                .addGap(85, 85, 85)
                .addComponent(btconsulta)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfmoradaF, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfnomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfsobrenomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfsobrenomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfmoradaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tffoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfemailF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btinserir)
                    .addComponent(btalterar)
                    .addComponent(btexcluir)
                    .addComponent(btconsulta))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinserirActionPerformed
//botao inserir - ok
     funcionarios f = new funcionarios();
     funcionariosdao dao = new funcionariosdao();
     f.setFunc_nome(tfnomeF.getText());
     f.setFunc_sobrenome(tfsobrenomeF.getText());
     f.setFunc_morada(tfmoradaF.getText());
     f.setFunc_fone(tffoneF.getText());
     f.setFunc_email(tfemailF.getText());
     dao.create(f);

     Table_Func.setValueAt(tfnomeF.getText(),Table_Func.getSelectedRow(),1);
     Table_Func.setValueAt(tfsobrenomeF.getText(),Table_Func.getSelectedRow(),2);
     Table_Func.setValueAt(tfmoradaF.getText(),Table_Func.getSelectedRow(),3);
     Table_Func.setValueAt(tffoneF.getText(),Table_Func.getSelectedRow(),4);
     Table_Func.setValueAt(tfemailF.getText(),Table_Func.getSelectedRow(),5);
     
     tfnomeF.setText("");
     tfsobrenomeF.setText("");
     tfmoradaF.setText("");
     tffoneF.setText("");
     tfemailF.setText("");
    }//GEN-LAST:event_btinserirActionPerformed

    private void btconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconsultaActionPerformed
        // TODO add your handling code here: botao consultar ok
    DefaultTableModel modelo = (DefaultTableModel) Table_Func.getModel();
    funcionariosdao a = new funcionariosdao();
    modelo.setNumRows(0);
    
     for (funcionarios x : a.read()) {
     modelo.addRow(new Object[]{
        
       x.getFunc_id(),
       x.getFunc_nome(),
       x.getFunc_sobrenome(),
       x.getFunc_morada(),
       x.getFunc_fone(),
       x.getFunc_email(),
        });           
        }
    }//GEN-LAST:event_btconsultaActionPerformed

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
        // TODO add your handling code here: botao alterar ok
        
     if(Table_Func.getSelectedRow() != -1){
     funcionarios u = new funcionarios();
     funcionariosdao dao = new funcionariosdao(); 
   
     u.setFunc_nome(tfnomeF.getText());
     u.setFunc_sobrenome(tfsobrenomeF.getText());
     u.setFunc_morada(tfmoradaF.getText());
     u.setFunc_fone(tffoneF.getText());
     u.setFunc_email(tfemailF.getText());
     u.setFunc_id((int)Table_Func.getValueAt(Table_Func.getSelectedRow(),0));
     dao.update(u); 
    }else{
       JOptionPane.showMessageDialog(null, "Escolha um funcionario para alterar os dados");     
     }   
     Table_Func.setValueAt(tfnomeF.getText(),Table_Func.getSelectedRow(),1);
     Table_Func.setValueAt(tfsobrenomeF.getText(),Table_Func.getSelectedRow(),2);
     Table_Func.setValueAt(tfmoradaF.getText(),Table_Func.getSelectedRow(),3);
     Table_Func.setValueAt(tffoneF.getText(),Table_Func.getSelectedRow(),4);
     Table_Func.setValueAt(tfemailF.getText(),Table_Func.getSelectedRow(),5);
    
      tfnomeF.setText("");
      tfsobrenomeF.setText("");
      tfmoradaF.setText("");
      tffoneF.setText("");
      tfemailF.setText("");
    }//GEN-LAST:event_btalterarActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        // TODO add your handling code here: ok, funciona bem
       
     if(Table_Func.getSelectedRow() != -1){
         
     funcionarios u = new funcionarios();
     funcionariosdao dao = new funcionariosdao();
     u.setFunc_id((int) Table_Func.getValueAt(Table_Func.getSelectedRow(),0));
     dao.delete(u);   
         
      tfnomeF.setText("");
      tfsobrenomeF.setText("");
      tfmoradaF.setText("");
      tffoneF.setText("");
      tfemailF.setText("");
     }else{
         JOptionPane.showMessageDialog(null, "Selecione um funcionario para excluir");
     }   
    }//GEN-LAST:event_btexcluirActionPerformed

    private void Table_FuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_FuncMouseClicked
        // TODO add your handling code here: evento do mouse
     if(Table_Func.getSelectedRow() != -1){ 
         
      tfnomeF.setText(String.valueOf(Table_Func.getValueAt(Table_Func.getSelectedRow(),1)));
      tfsobrenomeF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(),2).toString());
      tfmoradaF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(), 3).toString());
      tffoneF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(),4).toString());
      tfemailF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(), 5).toString());
     }   
    }//GEN-LAST:event_Table_FuncMouseClicked

    private void Table_FuncKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_FuncKeyPressed
        // TODO add your handling code here: evento do teclado
      if(Table_Func.getSelectedRow() != -1){ 
         
      tfnomeF.setText(String.valueOf(Table_Func.getValueAt(Table_Func.getSelectedRow(),1)));
      tfsobrenomeF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(),2).toString());
      tfmoradaF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(), 3).toString());
      tffoneF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(),4).toString());
      tfemailF.setText(Table_Func.getValueAt(Table_Func.getSelectedRow(), 5).toString());
     }       
    }//GEN-LAST:event_Table_FuncKeyPressed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Func;
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btconsulta;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btinserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfemailF;
    private javax.swing.JTextField tffoneF;
    private javax.swing.JTextField tfmoradaF;
    private javax.swing.JTextField tfnomeF;
    private javax.swing.JTextField tfsobrenomeF;
    // End of variables declaration//GEN-END:variables
}
